services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_files:/home/app/static
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

  db:
    image: postgres 
    env_file:
      - .env.prod 
    volumes:
      - pg_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    depends_on:
      - nginx 

  backend:
    build: .
    volumes:
      - static_files:/home/app/static
      # - venv:/home/app/venv
    env_file:
      - .env.prod
    expose:
      - 8000
    command: gunicorn Cinema.wsgi:application --bind 0.0.0.0:8000


# run this only one time, whenever else it would be saved in volume pg_data
#exec python manage.py migrate
# run python parsers
# can also be helpfull python manage.py loaddata dump_data ( delete contenttypes if needed) 

volumes:
  pg_data:
  static_files:
  # venv:
