# Generated by Django 4.2.3 on 2023-08-01 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FilmLibrary', '0005_alter_film_description_alter_film_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('longitude', models.CharField(default='76.934287', max_length=200)),
                ('lattitude', models.CharField(default='43.233651', max_length=200)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(blank=True, null=True)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city_cinemas.cinema')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FilmLibrary.film')),
            ],
        ),
        migrations.AddField(
            model_name='cinema',
            name='movies',
            field=models.ManyToManyField(through='city_cinemas.Schedule', to='FilmLibrary.film'),
        ),
    ]
