# Generated by Django 4.2.3 on 2023-08-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_cinemas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
