# Generated by Django 4.2.3 on 2023-08-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_cinemas', '0002_schedule_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_num', models.IntegerField()),
                ('seat_num', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='cinema',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='price',
            field=models.IntegerField(default=1500),
        ),
        migrations.AddField(
            model_name='schedule',
            name='selected_seats',
            field=models.ManyToManyField(related_name='session', to='city_cinemas.seat', verbose_name='Занятые места'),
        ),
    ]
