# Generated by Django 4.2.3 on 2023-07-26 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('career', models.CharField(max_length=200)),
                ('slug', models.SlugField(verbose_name='На английском')),
                ('date_of_birth', models.CharField(max_length=100, verbose_name='Дата рождения')),
                ('age', models.CharField(max_length=200)),
                ('biography', models.TextField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('career', models.CharField(max_length=200)),
                ('slug', models.SlugField(verbose_name='На английском')),
                ('date_of_birth', models.CharField(max_length=100, verbose_name='Дата рождения')),
                ('age', models.CharField(max_length=200)),
                ('biography', models.TextField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=5)),
                ('slug', models.SlugField()),
                ('year', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('country', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('length', models.CharField(max_length=100, verbose_name='Продолжительность')),
                ('acceptable_age', models.IntegerField(verbose_name='Возрастное ограничение')),
                ('budget', models.IntegerField(verbose_name='Бюджет')),
                ('actors', models.ManyToManyField(related_name='films', to='FilmLibrary.actor')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produced_films', to='FilmLibrary.director')),
                ('genres', models.ManyToManyField(to='FilmLibrary.genre', verbose_name='Жанры')),
            ],
        ),
    ]
