# Generated by Django 4.2.3 on 2023-07-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FilmLibrary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='zodiac_sign',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='director',
            name='zodiac_sign',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
