# Generated by Django 4.2.3 on 2023-07-28 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FilmLibrary', '0002_actor_zodiac_sign_director_zodiac_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='rating_counts',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='country',
            field=models.CharField(max_length=200, verbose_name='Страна выхода'),
        ),
        migrations.AlterField(
            model_name='film',
            name='director',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='produced_films', to='FilmLibrary.director'),
        ),
        migrations.AlterField(
            model_name='film',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('films', models.ManyToManyField(related_name='collections', to='FilmLibrary.film')),
            ],
        ),
    ]
