# Generated by Django 4.2.3 on 2023-08-01 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FilmLibrary', '0004_alter_actor_age_alter_actor_biography_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='description',
            field=models.TextField(blank=True, default='Нет описания'),
        ),
        migrations.AlterField(
            model_name='film',
            name='length',
            field=models.CharField(default='1 час 30 минут', max_length=100, verbose_name='Продолжительность'),
        ),
    ]
