# Generated by Django 4.2.3 on 2023-08-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FilmLibrary', '0005_alter_film_description_alter_film_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='slug',
            field=models.SlugField(max_length=250),
        ),
    ]
